#!/usr/bin/env sh 

TMPFILE="$(mktemp)";

sudo true;

rate-mirrors --save="$TMPFILE" arch

sudo mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
sudo mv "$TMPFILE" /etc/pacman.d/mirrorlist

sudo paccache -rk3

paru -Sc --aur --noconfirm
paru -Syyu --noconfirm
